# -*- coding: utf-8 -*-
"""1_outliers_percentile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L-N2t21xkuVGOOSG-jxx5dQWA5FOjfnO
"""

import pandas as pd
import streamlit as st

df = pd.read_csv("heights.csv")
st.dataframe(df.head())

st.subheader("Detect Outliers Using Percentiles")

max_threshold = df["height"].quantile(0.95)
min_threshold = df["height"].quantile(0.05)

st.write(max_threshold)
st.write(min_threshold)

st.dataframe(df[df["height"] > max_threshold])
st.dataframe(df[df["height"] < min_threshold])

filtered_df = df[
    (df["height"] < max_threshold) &
    (df["height"] > min_threshold)
]

st.dataframe(filtered_df)
"""<h3 style='color:purple'>Now lets explore banglore property prices dataset</h3>"""

df = pd.read_csv("bhp.csv")
st.dataframe(df.head())

st.write(df.shape)

st.dataframe(df.describe())
"""**Explore samples that are above 99.90% percentile and below 1% percentile rank**"""

min_threshold, max_threshold = df.price_per_sqft.quantile([0.001, 0.999])

st.write("Minimum Threshold:", min_threshold)
st.write("Maximum Threshold:", max_threshold)

st.dataframe(df[df.price_per_sqft < min_threshold])
st.dataframe(df[df.price_per_sqft > max_threshold])

"""<h3 style='color:purple'>Remove outliers</h3>"""

df2 = df[(df.price_per_sqft<max_threshold) & (df.price_per_sqft>min_threshold)]
st.write(df2.shape)

st.dataframe(df2.describe())
"""<h3 style='color:purple'>Exercise</h3>

Use this air bnb new york city [data set](https://www.kaggle.com/dgomonov/new-york-city-airbnb-open-data/data) and remove outliers using percentile based on price per night for a given apartment/home. You can use suitable upper and lower limits on percentile based on your intuition.
Your goal is to come up with new pandas dataframe that doesn't have the outliers present in it.

[Solution](https://github.com/codebasics/py/tree/master/ML/FeatureEngineering/1_outliers/Exercise/1_outliers_percentile_exercise.ipynb)
"""
