# -*- coding: utf-8 -*-
"""Linear Regression Deployment on streamLit .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19X1VJGfFofHO5mMV-ohidfL3mrN_Jj8a
"""

import streamlit as st
import pandas as pd
from sklearn.logistic_model import LogisticRegression

# -----------------------------------
# Page Configuration
# -----------------------------------
st.set_page_config(
    page_title="Insurance Policy Prediction",
    page_icon="🏠",
    layout="centered"
)

st.title("🏠Insurance Policy Prediction")
st.write("Predict Insurance Policy using Logistic Regression")

# -----------------------------------
# Load Dataset
# -----------------------------------
df = pd.read_csv("insurance_data.csv")

st.subheader("Dataset")
st.dataframe(df)

# -----------------------------------
# Train Model
# -----------------------------------
X_train, X_test, y_train, y_test = train_test_split(df[['age']],df.bought_insurance,train_size=0.8)

model = LogisticRegression()
model.fit(X, y)

# -----------------------------------
# User Input
# -----------------------------------
st.subheader("Enter Person Name")

area = st.number_input(
    "Age (In years )",
    min_value=10,
    max_value=65,
    value=18,
    step=1
)

# -----------------------------------
# Prediction
# -----------------------------------
if st.button("Predict Age"):

    prediction = model.predict([[age]])

    st.success(f"Predicted Age: {prediction[0]:,.2f}")

# -----------------------------------
# Model Information
# -----------------------------------
st.subheader("Model Details")

st.write("Coefficient:", model.coef_[0])
st.write("Intercept:", model.intercept_)
